DoAnQuanLySach/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnQuanLySach.Models;

namespace DoAnQuanLySach.Controllers
{
    public class BooksController : Controller
    {
        private BookManagerDbEntities db = new BookManagerDbEntities();

        // GET: Books
        public ActionResult Index()
        {
            var categories = from c in db.Categories select c;
            ViewBag.categoryID = new SelectList(categories, "CategoryID", "CategoryName");
            var books = db.Books.Include(b => b.Category);
            return View(books.ToList());
        }
        public ActionResult Listbooks(string SearchString,string Publisherr, int categoryID = 0)
        {
            var books = from s in db.Books select s;
            var categories = from c in db.Categories select c;
            ViewBag.categoryID = new SelectList(categories, "CategoryId", "CategoryName");
            ViewBag.category = categories.ToList();
            Session["Timkiem"] = "-1";
            if (!String.IsNullOrEmpty(SearchString))
            {
                books = books.Where(s => s.Title.Contains(SearchString));
                Session["Timkiem"] = "1";
            }
            if (!String.IsNullOrEmpty(Publisherr))
            {
                books = books.Where(s => s.PublisherName.Contains(Publisherr));
                Session["Timkiem"] = "1";
            }
            if (categoryID != 0)
            {
                books = books.Where(x => x.CategoryId == categoryID);
                Session["Timkiem"] = "1";
            }
            books = books.OrderByDescending(s => s.Price);
            return View(books.ToList());
        }
        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookId,Title,AuthorName,Price,Amount,Year,CoverPage,CategoryId,PublisherName")] Book book, HttpPostedFileBase file)
        {
            System.Diagnostics.Debug.WriteLine(file);
            ViewBag.error = "";
            if (file != null) ViewBag.error = file.FileName; else 
            if (file == null ) ViewBag.error = "ASSSSSSSSSSSSSS";
            else 
            if (ModelState.IsValid && book.Title != null && book.AuthorName != null && book.Price != null && book.Year != null && book.PublisherName != null && file != null)
            {
                if(book.Price<0) ViewBag.error = "Giá tiền phải là số dương";
                else if (book.Year < 0) ViewBag.error = "Năm phải là số dương";
                else if (book.Amount < 0) ViewBag.error = "Số lượng phải là số dương";
                else
                {
                    if (file != null)
                    {
                        //file.SaveAs(HttpContext.Server.MapPath("~/Images/")+ file.FileName);
                        book.CoverPage = "/Content/images/" + file.FileName;

                    }
                    var list = db.Books;
                    int tmp = 0;
                    for (int i = 1; i <= list.ToList().Count; i++)
                    {
                        Book user = db.Books.Find(i);
                        if (user == null) tmp = i;
                    }
                    book.BookId = tmp;
                    db.Books.Add(book);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else ViewBag.error = "Nhập đữ liệu còn trống";
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", book.CategoryId);
            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", book.CategoryId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookId,Title,AuthorName,Price,Amount,Year,CoverPage,CategoryId,PublisherName")] Book book, HttpPostedFileBase file)
        {
            System.Diagnostics.Debug.WriteLine(file);

            ViewBag.error = "";
            if (ModelState.IsValid && book.Title != null && book.AuthorName != null && book.Price != null && book.Year != null && book.PublisherName != null && file != null)
            {
                if (book.Price < 0) ViewBag.error = "Giá tiền phải là số dương";
                else if (book.Year < 0) ViewBag.error = "Năm phải là số dương";
                else if (book.Amount < 0) ViewBag.error = "Số lượng phải là số dương";
                else
                {
                    if (file != null)
                    {
                        //file.SaveAs(HttpContext.Server.MapPath("~/Images/")+ file.FileName);
                        book.CoverPage = "/Content/images/" + file.FileName;

                    }
                    if (book.Price < 0) ViewBag.error = "Giá tiền phải là số dương";
                    else if (book.Year < 0) ViewBag.error = "Năm phải là số dương";
                    else
                    {
                        if (file != null)
                        {
                            //file.SaveAs(HttpContext.Server.MapPath("~/Images/")+ file.FileName);
                            book.CoverPage = "/Content/images/" + file.FileName;

                        }
                        db.Entry(book).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }


            }
            else ViewBag.error = "Nhập đữ liệu còn trống";

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", book.CategoryId);
            return View(book);
        }
        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnQuanLySach/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnQuanLySach.Models;

namespace DoAnQuanLySach.Controllers
{
    public class CartsController : Controller
    {
        private BookManagerDbEntities db = new BookManagerDbEntities();

        // GET: Carts
        public ActionResult Index()
        {
            var carts = db.Carts.Include(c => c.Userr);
            return View(carts.ToList());
        }
        public ActionResult BaoCao(int Thang = 0, int Quy = 0, int Nam = 0)
        {
            var carts = db.Carts.Include(c => c.Userr);
            Session["Thang"] = Thang;
            Session["Quy"] = Quy;
            Session["Nam"] = Nam;
            Session["Tongtien"] = 0;
            if (Thang != 0)
            {
                carts = carts.Where(s => s.Datebuy.Value.Month == Thang);
            }
            if (Quy != 0)
            {
                if (Quy == 1) carts = carts.Where(s => s.Datebuy.Value.Month >= 0 && s.Datebuy.Value.Month <= 3);
                else if (Quy == 2) carts = carts.Where(s => s.Datebuy.Value.Month >= 4 && s.Datebuy.Value.Month <= 6);
                else if (Quy == 3) carts = carts.Where(s => s.Datebuy.Value.Month >= 7 && s.Datebuy.Value.Month <= 9);
                else if (Quy == 4) carts = carts.Where(s => s.Datebuy.Value.Month >= 10 && s.Datebuy.Value.Month <= 12);
            }
            if (Nam != 0)
            {
                carts = carts.Where(s => s.Datebuy.Value.Year == Nam);
            }
            foreach (var item in carts)
            {
                Session["Tongtien"] = double.Parse(Session["Tongtien"].ToString()) + item.Total;
            }
            return View(carts.ToList());

        }
        // GET: Carts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // GET: Carts/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.Userrs, "UserId", "Username");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CartId,Datebuy,UserID,Total")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.Userrs, "UserId", "Username", cart.UserID);
            return View(cart);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.Userrs, "UserId", "Username", cart.UserID);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CartId,Datebuy,UserID,Total")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.Userrs, "UserId", "Username", cart.UserID);
            return View(cart);
        }

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cart cart = db.Carts.Find(id);
            db.Carts.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnQuanLySach/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnQuanLySach.Models;
namespace DoAnQuanLySach.Controllers
{
    public class LoginController : Controller
    {
        private BookManagerDbEntities db = new BookManagerDbEntities();
        // GET: Login
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            var userr = from s in db.Userrs select s;
            userr = userr.Where(s => s.Username.CompareTo(username) == 0);
            foreach (var item in userr)
            {
                if (item.Password.CompareTo(password)==0)
                {
                    var categories = from c in db.Categories select c;
                    ViewBag.categoryID = new SelectList(categories, "CategoryID", "CategoryName");
                    Session["username"] = item.Username;
                    Session["accountname"] = item.Name;
                    Session["role"] = item.TypeID;
                    Session["userid"] = item.UserId;
                    ViewBag.error = "Good";
                    if(item.TypeID==1)
                    return View("~/Views/Home/Admin.cshtml");
                    else if (item.TypeID == 2)
                        return View("~/Views/Home/NhanVien.cshtml");
                    else return View("~/Views/Home/Index.cshtml");
                }    
            }
            Session["username"] = "";
            ViewBag.error = "Tên đăng nhập hoặc mật khẩu không hợp lệ";
            return View("Index");
        }
        [HttpGet]
        public ActionResult Logout()
        {
            Session.Remove("username"); Session.Remove("role"); Session.Remove("userid"); Session.Remove("accountname");
            return RedirectToAction("Index");
        }
    }
}

DoAnQuanLySach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body >
    <div class="navbar navbar-expand-sm bg-dark navbar-dark navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mega Library", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    <li>@Html.ActionLink("Trang chủ", "Listbooks", "Books", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Loại sách
                        </a>
                        <div class="dropdown-menu bg-dark dropdown-menu-dark">
                            <p style="padding-left:10px;">@Html.ActionLink("Tất cả các loại", "Index", "Categories", new { area = "" }, new { @class = "dropdown-item" })</p>
                            <div class="dropdown-divider"></div>
                            <p style="padding-left:10px;">@Html.ActionLink("Chính trị – pháp luật", "Details", "Categories", new { id = 1 }, new { @class = "dropdown-item" })</p>
                            <div class="dropdown-divider"></div>
                            <p style="padding-left:10px;">@Html.ActionLink("Khoa học công nghệ – Kinh tế", "Details", "Categories", new { id = 2 }, new { @class = "dropdown-item" })</p>
                            <div class="dropdown-divider"></div>
                            <p style="padding-left:10px;">@Html.ActionLink("Văn học nghệ thuật", "Details", "Categories", new { id = 3 }, new { @class = "dropdown-item" })</p>
                            <div class="dropdown-divider"></div>
                            <p style="padding-left:10px;">@Html.ActionLink("Văn hóa xã hội – Lịch sử", "Details", "Categories", new { id = 4 }, new { @class = "dropdown-item" })</p>
                            <div class="dropdown-divider"></div>
                            <p style="padding-left:10px;">@Html.ActionLink("Giáo trình", "Details", "Categories", new { id = 5 }, new { @class = "dropdown-item" })</p>
                            <div class="dropdown-divider"></div>
                            <p style="padding-left:10px;">@Html.ActionLink("Truyện, tiểu thuyết", "Details", "Categories", new { id = 6 }, new { @class = "dropdown-item" })</p>
                            <div class="dropdown-divider"></div>
                            <p style="padding-left:10px;">@Html.ActionLink("Tâm lý, tâm linh, tôn giáo", "Details", "Categories", new { id = 7 }, new { @class = "dropdown-item" })</p>
                            <div class="dropdown-divider"></div>
                            <p style="padding-left:10px;">@Html.ActionLink("Thiếu nhi", "Details", "Categories", new { id = 8 }, new { @class = "dropdown-item" })</p>

                        </div>
                    </li>
                </ul>

                @if (Session["username"] != "" && Session["username"] != null)
                {
                    if (Session["role"].ToString().CompareTo("1") == 0)
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Quản lý về người dùng
                                </a>
                                <div class="dropdown-menu bg-dark dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <p style="padding-left:10px;">@Html.ActionLink("Loại người dùng", "Index", "TypeUsers", new { area = "" }, new { @class = "dropdown-item" })</p>
                                    <div class="dropdown-divider"></div>
                                    <p style="padding-left:10px;">@Html.ActionLink("Người dùng", "Index", "Userrs", new { area = "" }, new { @class = "dropdown-item" })</p>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Quản lý về giao dịch của người dùng
                                </a>
                                <div class="dropdown-menu bg-dark dropdown-menu-dark">
                                    <p style="padding-left:10px;">@Html.ActionLink("Báo cáo", "BaoCao", "Carts", new { area = "" }, new { @class = "dropdown-item" })</p>
                                    <div class="dropdown-divider"></div>
                                    <p style="padding-left:10px;">@Html.ActionLink("Giỏ hàng", "Index", "Carts", new { area = "" }, new { @class = "dropdown-item" })</p>
                                    <div class="dropdown-divider"></div>
                                    <p style="padding-left:10px;">@Html.ActionLink("Chi tiết giỏ hàng", "Index", "CartDetails", new { area = "" }, new { @class = "dropdown-item" })</p>
                                </div>
                            </li>
                        </ul>
                    }
                    else
                    {
                        if (Session["role"].ToString().CompareTo("2") == 0)
                        {
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Quản lý về sách
                    </a>
                    <div class="dropdown-menu bg-dark dropdown-menu-dark">
                        <p style="padding-left:10px;">@Html.ActionLink("Loại sách", "Index", "Categories", new { area = "" }, new { @class = "dropdown-item" })</p>
                        <div class="dropdown-divider"></div>
                        <p style="padding-left:10px;">@Html.ActionLink("Sách", "Index", "Books", new { area = "" }, new { @class = "dropdown-item" })</p>
                        <div class="dropdown-divider"></div>
                        <p style="padding-left:10px;">@Html.ActionLink("Chương sách", "Index", "Chapters", new { area = "" }, new { @class = "dropdown-item" })</p>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Quản lý về nhập sách
                    </a>
                    <div class="dropdown-menu bg-dark dropdown-menu-dark">
                        <p style="padding-left:10px;">@Html.ActionLink("Nhập đơn hàng", "Index", "NhapHang", new { area = "" }, new { @class = "dropdown-item" })</p>
                        <div class="dropdown-divider"></div>
                        <p style="padding-left:10px;">@Html.ActionLink("Đơn nhập hàng", "Index", "Imports", new { area = "" }, new { @class = "dropdown-item" })</p>
                        <div class="dropdown-divider"></div>
                        <p style="padding-left:10px;">@Html.ActionLink("Chi tiết đơn nhập hàng", "Index", "ImportDetails", new { area = "" }, new { @class = "dropdown-item" })</p>
                    </div>
                </li>
            </ul>
                        }
                    }
                }
            </div>
            @if (Session["username"] != "" && Session["username"] != null)
            {
        <form class="d-flex">
            <a class="btn btn-success" href="/Userrs/Details/@Session["userid"]" style="font-weight:200;"> <span class="glyphicon glyphicon-user"></span></a>
            <a class="btn btn-info" href="/GioHang/index" style="font-weight:200;"> <span class="glyphicon glyphicon-shopping-cart"></span></a>
            <br />
            <a href="@Url.Action("Logout", "Login")" class="btn btn-danger" type="button">Đăng xuất</a>
        </form>
            }
            else
            {             
        <form class="d-flex">
            <a class="btn btn-info" href="/Userrs/Signup" style="font-weight:200;">Đăng kí</a>
            <a href="/Login/Index" class="btn btn-danger" type="button">Đăng nhập</a>
        </form>
            }
        </div>
    </div>
    <div class="container body-content"  >
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Quản lý sách</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>