DoAnQuanLySach/Models/Import.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLySach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Import()
        {
            this.ImportDetails = new HashSet<ImportDetail>();
        }
    
        public int ImportId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ExportName { get; set; }
        public Nullable<double> Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportDetail> ImportDetails { get; set; }
    }
}

DoAnQuanLySach/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnQuanLySach.Models;

namespace DoAnQuanLySach.Controllers
{
    public class BooksController : Controller
    {
        private BookManagerDbEntities db = new BookManagerDbEntities();

        // GET: Books
        public ActionResult Index()
        {
            var categories = from c in db.Categories select c;
            ViewBag.categoryID = new SelectList(categories, "CategoryID", "CategoryName");
            var books = db.Books.Include(b => b.Category);
            return View(books.ToList());
        }
        public ActionResult Listbooks(string SearchString,string Publisherr, int categoryID = 0)
        {
            var books = from s in db.Books select s;
            var categories = from c in db.Categories select c;
            ViewBag.categoryID = new SelectList(categories, "CategoryId", "CategoryName");
            ViewBag.category = categories.ToList();
            Session["Timkiem"] = "-1";
            if (!String.IsNullOrEmpty(SearchString))
            {
                books = books.Where(s => s.Title.Contains(SearchString));
                Session["Timkiem"] = "1";
            }
            if (!String.IsNullOrEmpty(Publisherr))
            {
                books = books.Where(s => s.PublisherName.Contains(Publisherr));
                Session["Timkiem"] = "1";
            }
            if (categoryID != 0)
            {
                books = books.Where(x => x.CategoryId == categoryID);
                Session["Timkiem"] = "1";
            }
            books = books.OrderByDescending(s => s.Price);
            return View(books.ToList());
        }
        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookId,Title,AuthorName,Price,Amount,Year,CoverPage,CategoryId,PublisherName")] Book book, HttpPostedFileBase file)
        {
            System.Diagnostics.Debug.WriteLine(file);
            ViewBag.error = "";
            if (file != null) ViewBag.error = file.FileName; else 
            if (file == null ) ViewBag.error = "ASSSSSSSSSSSSSS";
            else 
            if (ModelState.IsValid && book.Title != null && book.AuthorName != null && book.Price != null && book.Year != null && book.PublisherName != null && file != null)
            {
                if(book.Price<0) ViewBag.error = "Giá tiền phải là số dương";
                else if (book.Year < 0) ViewBag.error = "Năm phải là số dương";
                else if (book.Amount < 0) ViewBag.error = "Số lượng phải là số dương";
                else
                {
                    if (file != null)
                    {
                        //file.SaveAs(HttpContext.Server.MapPath("~/Images/")+ file.FileName);
                        book.CoverPage = "/Content/images/" + file.FileName;

                    }
                    var list = db.Books;
                    int tmp = 0;
                    for (int i = 1; i <= list.ToList().Count; i++)
                    {
                        Book user = db.Books.Find(i);
                        if (user == null) tmp = i;
                    }
                    book.BookId = tmp;
                    db.Books.Add(book);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else ViewBag.error = "Nhập đữ liệu còn trống";
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", book.CategoryId);
            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", book.CategoryId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookId,Title,AuthorName,Price,Amount,Year,CoverPage,CategoryId,PublisherName")] Book book, HttpPostedFileBase file)
        {
            System.Diagnostics.Debug.WriteLine(file);

            ViewBag.error = "";
            if (ModelState.IsValid && book.Title != null && book.AuthorName != null && book.Price != null && book.Year != null && book.PublisherName != null && file != null)
            {
                if (book.Price < 0) ViewBag.error = "Giá tiền phải là số dương";
                else if (book.Year < 0) ViewBag.error = "Năm phải là số dương";
                else if (book.Amount < 0) ViewBag.error = "Số lượng phải là số dương";
                else
                {
                    if (file != null)
                    {
                        //file.SaveAs(HttpContext.Server.MapPath("~/Images/")+ file.FileName);
                        book.CoverPage = "/Content/images/" + file.FileName;

                    }
                    if (book.Price < 0) ViewBag.error = "Giá tiền phải là số dương";
                    else if (book.Year < 0) ViewBag.error = "Năm phải là số dương";
                    else
                    {
                        if (file != null)
                        {
                            //file.SaveAs(HttpContext.Server.MapPath("~/Images/")+ file.FileName);
                            book.CoverPage = "/Content/images/" + file.FileName;

                        }
                        db.Entry(book).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }


            }
            else ViewBag.error = "Nhập đữ liệu còn trống";

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", book.CategoryId);
            return View(book);
        }
        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnQuanLySach/Controllers/ImportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnQuanLySach.Models;

namespace DoAnQuanLySach.Controllers
{
    public class ImportsController : Controller
    {
        private BookManagerDbEntities db = new BookManagerDbEntities();

        // GET: Imports
        public ActionResult Index(int Thang=0, int Quy=0, int Nam=0)
        {
            Session["Thang"] = Thang;
            Session["Quy"] = Quy;
            Session["Nam"] = Nam;
            Session["Tongtien"] = 0;
            var imports = from s in db.Imports select s;
            if (Thang != 0)
            {
                imports = imports.Where(s => s.Date.Value.Month==Thang);
            }
            if (Quy != 0) 
            {
                if(Quy==1) imports = imports.Where(s => s.Date.Value.Month >=0 && s.Date.Value.Month <= 3);
                else if (Quy == 2) imports = imports.Where(s => s.Date.Value.Month >= 4 && s.Date.Value.Month <= 6);
                else if (Quy == 3) imports = imports.Where(s => s.Date.Value.Month >= 7 && s.Date.Value.Month <= 9);
                else if (Quy == 4) imports = imports.Where(s => s.Date.Value.Month >= 10 && s.Date.Value.Month <= 12);
            }
            if (Nam != 0) 
            {
                imports = imports.Where(s => s.Date.Value.Year == Nam);
            }
            foreach(var item in imports)
            {
                Session["Tongtien"] = double.Parse(Session["Tongtien"].ToString()) + item.Total;
            }
            return View(imports.ToList());
        }

        // GET: Imports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Import import = db.Imports.Find(id);
            if (import == null)
            {
                return HttpNotFound();
            }
            return View(import);
        }

        // GET: Imports/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Imports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ImportId,Date,ExportName,Total")] Import import)
        {
            if (ModelState.IsValid)
            {
                var list = db.Imports;
                int tmp = 0;
                for (int i = 1; i <= list.ToList().Count; i++)
                {
                    Import user = db.Imports.Find(i);
                    if (user == null) tmp = i;
                }
                import.ImportId = tmp;
                db.Imports.Add(import);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(import);
        }

        // GET: Imports/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Import import = db.Imports.Find(id);
            if (import == null)
            {
                return HttpNotFound();
            }
            return View(import);
        }

        // POST: Imports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ImportId,Date,ExportName,Total")] Import import)
        {
            if (ModelState.IsValid)
            {
                db.Entry(import).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(import);
        }

        // GET: Imports/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Import import = db.Imports.Find(id);
            if (import == null)
            {
                return HttpNotFound();
            }
            return View(import);
        }

        // POST: Imports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Import import = db.Imports.Find(id);
            db.Imports.Remove(import);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnQuanLySach/Views/Imports/Create.cshtml
@model DoAnQuanLySach.Models.Import

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Import</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExportName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExportName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExportName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAnQuanLySach/Views/Imports/Delete.cshtml
@model DoAnQuanLySach.Models.Import

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Import</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExportName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExportName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoAnQuanLySach/Views/Imports/Details.cshtml
@model DoAnQuanLySach.Models.Import

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Import</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExportName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExportName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>
</div>
<h4>Chi tiết đơn nhập</h4>
<table class="table table-bordered">
    <tr>
        <th>ID sách</th>
        <th>Tên sách</th>
        <th>Giá tiền một quyển</th>
        <th>Số lượng</th>
    </tr>
    @if (Model.ImportDetails.Count > 0)
    {
        foreach (var item in Model.ImportDetails)
        {
<tr>
    <td>@item.BookId</td>
    <td><a target="_blank" href="@Url.Action("Details", "Books", new { id = item.BookId })"> @item.Book.Title </a></td>
    <td>@item.Price vnđ </td>
    <td>@item.Quantity</td>
</tr>
        }
    }
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ImportId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DoAnQuanLySach/Views/Imports/Edit.cshtml
@model DoAnQuanLySach.Models.Import

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Import</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ImportId)

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExportName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExportName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExportName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAnQuanLySach/Views/Imports/Index.cshtml
@model IEnumerable<DoAnQuanLySach.Models.Import>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Báo cáo nhập sách</h2>
@using (Html.BeginForm("Index", "Imports", FormMethod.Get))
{
    <h3>Tìm kiếm sách</h3>

    <table class="table">
        <tr>
            <td>
                <span class="input-group-text" style="width:300px;margin:0px;font-size:15px">
                    Theo tháng:
                    <select id="Thang" name="Thang" class="form-control" value>
                        <option value=0>---Chọn tháng---</option>
                        <option value=1>1</option>
                        <option value=2>2</option>
                        <option value=3>3</option>
                        <option value=4>4</option>
                        <option value=5>5</option>
                        <option value=6>6</option>
                        <option value=7>7</option>
                        <option value=8>8</option>
                        <option value=9>9</option>
                        <option value=10>10</option>
                        <option value=11>11</option>
                        <option value=12>12</option>
                    </select>
                </span>
            </td>
            <td>
                <span class="input-group-text" style="width:320px;height:43.5px ;margin:0px;font-size:15px">
                    Theo quý:
                    <select id="Quy" name="Quy" class="form-control">
                        <option value=0>---Chọn quý---</option>
                        <option value=1>Từ tháng 1 -> tháng 3</option>
                        <option value=2>Từ tháng 4 -> tháng 6</option>
                        <option value=3>Từ tháng 7 -> tháng 9</option>
                        <option value=4>Từ tháng 10 -> tháng 12</option>
                    </select>
                </span>
            </td>
            <td>
                <span class="input-group-text" style="width:300px;margin:0px;font-size:15px">
                    Theo năm:
                    <input type="number" id="Nam" name="Nam" placeholder="Năm" />
                </span>
            </td>
            <td>
                <input type="submit" value="Search" class="btn btn-danger" style="margin-top:5px" />
            </td>

        </tr>
    </table>
}
@if (Session["Thang"].ToString().CompareTo("0") != 0 || Session["Quy"].ToString().CompareTo("0") != 0 || Session["Nam"].ToString().CompareTo("0") != 0)
{<h3>Báo cáo theo</h3>}
<table class="table">
    <tr>
        @if (Session["Thang"].ToString().CompareTo("0")!=0) { <th>Tháng: @Session["Thang"]</th>}
            @if (Session["Quy"].ToString().CompareTo("1") == 0)
            {<th>Quý: tháng 1 - 3</th>}
            else
            {
                if (Session["Quy"].ToString().CompareTo("2") == 0)
                { <th>Quý: tháng 4 - 6</th>}
                else
                {
                    if (Session["Quy"].ToString().CompareTo("3") == 0)
                    { <th>Quý: tháng 7 - 9</th>}
                    else if (Session["Quy"].ToString().CompareTo("4") == 0)
                    { <th>Quý: tháng 10 - 12</th>}
                }
            }
            @if (Session["Nam"].ToString().CompareTo("0") != 0)
            {<th>Năm: @Session["Nam"]</th>}
    </tr>
</table>
<h3>Chi tiết nhập</h3>
<table class="table">
    <tr>
        <th>
            Ngày nhập
        </th>
        <th>
            Người nhập
        </th>
        <th>
            Tổng tiền
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExportName)
            </td>
            <td>
                @string.Format("{0:#,##0}", item.Total) VNĐ
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.ImportId }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.ImportId }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.ImportId })
            </td>
        </tr>
    }

</table>
<h3>Tổng tiền : @string.Format("{0:#,##0}", @Session["Tongtien"]) vnđ</h3>